### ISSUE TITLE
HACS 404 Error: 0.3.0 update

### ISSUE THREAD

**Issue by brianhanifin** [custom-cards/decluttering-card#16]
I'm getting a 404 (file not found) error message when trying to update via HACS. I tried uninstalling, then reinstalling the card, and I rebooted my server, but I still cannot update to 0.3.0. If I select 0.2.0 from the HACS menu I can get the previous version installed.

**Comment by RomRider** [comment]
Update to the latest hacs or restart your home-assistant instance. I had the same issue.

**Comment by brianhanifin** [comment]
I am on the latest version of HACS (0.20.7).

OK, after some experimenting, I found that these steps resolved it for me:

1. Uninstall `decluttering-card`.
2. Restart Home Assistant (I did not have to reboot the server).
3. Use HACS to install `decluttering-card` 0.3.0.

Thanks for the advice! I was able to get it figured out.

**Comment by RomRider** [comment]
Thanks for the detailed report :)
