### ISSUE TITLE
Undefined Var errors with 2021.4

### ISSUE THREAD

**Issue by genem2** [custom-cards/decluttering-card#37]
HA 2021.4 introduced a new _feature_: [Warnings for undefined variables in Template](https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates)s.

This jams up decluttering-card if you keep a browsers open during HA restart. Lovelace tries to render the card, and HA starts spewing the warnings because they allow things to start before everything's ready.

I reported it [over here](https://community.home-assistant.io/t/please-suppress-undefined-var-errors-until-completes-startup/298779) as an enhancement, but they feel this should be an issue for the decluttering-card. Not sure if you can hold off until started or not...

**Release that introduces this issue:**
2021.4

**Description of problem:**

During a HA restart, Lovelace reports not all entities will be available until HA Completes starting, but if any browser window is open, Lovelace starts rendering that decluttering_templates card.

**Comment by RomRider** [comment]
What you reported is not decluttering-card. Decluttering-card doesn't render jinja templates so I'm not sure what you are talking about.

**Comment by genem2** [comment]
Apologies. 
(Hoping this full entry can be removed to prevent future search hits.)
