### ISSUE TITLE
Need to restart HA to see decluttering_template changes in dashboard

### ISSUE THREAD

**Issue by jchhenderson** [custom-cards/decluttering-card#49]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
HA core 2022.5.5, running on RPi 4B with DietPi 8.4.2 (Debian 11 'Bullseye')
Decluttering card: 0.6.3
HACS:  1.25.5 (rolled back to 1.24.5 and issue persisted)

**Last working release (if known):**
not known, but was working last week and so I _suspect_ HA core 2022.5.4

**Browser and Operating System:**
Mac app 2022.358 (MacOS 12.4)
Safari 15.5 (MacOS 12.4)
Firefox 100.0.2 (MacOS 12.4)
iOS app (iOS 15.5)

**Description of problem:**
I need to restart HA in order to see any changes made in my declutter.yaml file reflected in my dashboard.  Previously, I simply needed to refresh (clear cache).

**Javascript errors shown in the web inspector (if applicable):**
no error.

**Additional information:**
I am sure this was working for me last week.
The only change I can think of is updating HA itself from 2022.5.4 to 2022.5.5
I did update HACS, but I rolled that back to 1.24.5 and the problem persisted.

**Comment by jchhenderson** [comment]
OK, something else is going on as I have another instance running in docker on another Mac (same versions of MacOS, HA core & HACS) and changes are reflected after a refresh.

I will do some more testing to see what's different with my instance and report back here.  Until then, please donlt spend any time on this.

**Comment by ildar170975** [comment]
> I need to restart HA in order to see any changes made in my declutter.yaml file reflected in my dashboard. Previously, I simply needed to refresh (clear cache).

What do you by "clear cache"?
Where do you keep your decluttering templates?

**Comment by jchhenderson** [comment]
OK, got it ...mostly.

I am not sure if this is to do with the recent archiving of `kiosk_mode` (which I had to re-download outside of HACS) but my dashboards refresh perfectly in a browser with `kiosk_mode` off (url ends with `?disable_km`) which triggers a refresh in all other versions (iOS, macOS app etc etc).

> What do you by "clear cache"?
@ildar170975 hi - I may have used the wrong terminology, but by "clear cache" I meant reloading the page (in a bowser) from origin to remove any downloaded-and-cached elements that may not have otherwise been re-downloaded.

> Where do you keep your decluttering templates?
@ildar170975 I keep them in a single .yaml file that is called just before 'views:' in the dashboard.

**Comment by ildar170975** [comment]
Read this:
https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3233?u=ildar_gabdullin

**Comment by jchhenderson** [comment]
Thanks! ...but, as I wrote above, ` kiosk_mode` was interfering with refreshing.

**Comment by ildar170975** [comment]
Yes, that link was given only to share experience regarding storing templates & refreshing.

**Comment by jchhenderson** [comment]
thanks, I appreciate the gesture 👍
