### ISSUE TITLE
Broken in HomeAssistant beta (2023.4b0)

### ISSUE THREAD

**Issue by kulmegil** [custom-cards/decluttering-card#63]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

Home Assistant2023.4b0

**Last working release (if known):**

Home Assistant 2023.3.6

**Browser and Operating System:**

any

**Description of problem:**

Card is no longer able to load templates located in lovelace config.

This is caused by changes in dom structure in HA frontend and getLovelace() (from "custom-card-helpers" dependency) 
no longer returning lovelace config to Decluittering Card

**Javascript errors shown in the web inspector (if applicable):**

```
card custom:decluttering-card TypeError: can't access property "config", t is null
```

**Additional information:**

**Comment by t-n** [comment]
I found a workaround until we get a new release

- remove `www/community/decluttering-card/decluttering-card.js.gz`
- in `www/community/decluttering-card/decluttering-card.js` on line `850`, replace the entire line with       
`var e = document.querySelector("home-assistant");if (e = (e = (e = (e = (e = (e = (e = (e = e && e.shadowRoot) && e.querySelector("home-assistant-main")) && e.shadowRoot) && e.querySelector("mwc-drawer partial-panel-resolver")) || e) && e.querySelector("ha-panel-lovelace")) && e.shadowRoot) && e.querySelector("hui-root")) {`
(_or_ change `app-drawer-layout` to `mwc-drawer` and remove the following `&& e.shadowRoot`)

**Comment by kulmegil** [comment]
You just needed to replace "```app-drawer-layout partial-panel-resolver```" into "```app-drawer-layout, mwc-drawer partial-panel-resolver```" and it should work with both beta and previous versions as well.

**Comment by johntdyer** [comment]
Yea, neither @kulmegil  or @t-n 's method seem to be working for me...

**Comment by Mariusthvdb** [comment]
Thank you!

**Comment by kulmegil** [comment]
@RomRider thank you for fixing this one for us. Works well! 

@johntdyer it did work until beta 4 broke things again ;)

**Comment by eiiot** [comment]
Still broken in `2023.4.1` for me...

**Comment by firstof9** [comment]
Empty your browser cache and reload.

**Comment by SoulRaven** [comment]
same problem also on Home Assistant 2023.4.2 no change

**Comment by Mariusthvdb** [comment]
No it's not broken anymore. Just do what we have to do. Every time.
When a custom resource is updated..

Update via Hacs. Or edit the number manually with the 'cache-breaker' if using yaml.
