### ISSUE TITLE
Polymer will be deprecated in HA 2023.5

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/decluttering-card#66]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
2023.4
**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

Please see: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/ on the matter.

**Javascript errors shown in the web inspector (if applicable):**

<img width="1455" alt="Scherm­afbeelding 2023-04-06 om 15 18 16" src="https://user-images.githubusercontent.com/33354141/230390333-dbab952c-95e5-451d-9de9-484a702a674a.png">

**Additional information:**

Would be very much appreciated if you could update the card accordingly. There currently hardly is an alternative, so it would be a 'big deal' if we could no longer use our heavily decluttered Dashboards...

thanks for considering

**Comment by SoulRaven** [comment]
possibile same here,
Home Assistant 2023.4.2 with the latest version of the declutteing-card now i get in console this:

```
card custom:decluttering-card TypeError: Cannot read properties of null (reading 'config')
    at Pe.setConfig (decluttering-card.js:766:16)
    at a (create-element-base.ts:97:11)
    at create-element-base.ts:111:12
    at u (create-element-base.ts:215:12)
    at d (create-element-base.ts:172:12)
    at Module.w (create-card-element.ts:98:3)
    at kt._createCard (layout-card.js:64:1699)
    at layout-card.js:64:1933
    at Array.map (<anonymous>)
    at kt._createCards (layout-card.js:64:1920)
```

and in lovelace
`
Cannot read properties of null (reading 'config')
`

**Comment by Mariusthvdb** [comment]
That has nothing to do with this  topic.
Which is about Polymer.

Also, I'll close this, as decluttering seems to not use Polymer and won't be impacted .
