### ISSUE TITLE
Can you add HA cast support

### ISSUE THREAD

**Issue by Stephan296** [custom-cards/decluttering-card#9]
Can you add Home Assistant Cast support.
A comment on the HA forum is:

**The best thing is to reach out to the dev of the card. There are issues with the lit element and maybe even the local files they might be pulling…

Copy to clipboard
var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-view"));
if the corresponding bit at the end doesn’t say “hui-view” you can try editing it to say that… and make sure you change the version number in lovelace resources or it won’t load it.

That might make it work. I my case I also had to wrap a file URL to make it work as well.**

Can you do something with it?

Regards!

**Comment by RomRider** [comment]
I'm super busy right now but will check that soon.
PRs are always welcome, though ;)

**Comment by RomRider** [comment]
Fixed in `0.3.0`
